### ISSUE TITLE
PARAlyzer fail with error message

### ISSUE THREAD

**Issue by santataRU** [ohlerlab/PARpipe#4]
Dear Ohlerlab members,

I run PARAlyzer alone to process my PAR-CLIP data but failed with message as below:

**(base) bieniaszs-ipro:hg19_NL4_3 bieniaszlab$ PARAlyzer 128G hnRNPU_NL43.ini 
Running PARalyzer v1.5
Parsing SAM file(s)...Done
Creating Read Groups & Clusters...Exception in thread "main" java.lang.Exception: * is not found in the .2bit file
	at MyTwoBitParser.loadChromosome(MyTwoBitParser.java:58)
	at MyTwoBitParser.getSequence(MyTwoBitParser.java:118)
	at PARalyze.main(PARalyze.java:204)**

My 2bit file was generated by Fatotwobit tool, I really appreciate any input from you.

My ini file content is below:
BANDWIDTH=3
CONVERSION=T>C
MINIMUM_READ_COUNT_PER_GROUP=5
MINIMUM_READ_COUNT_PER_CLUSTER=5
MINIMUM_READ_COUNT_FOR_KDE=5
MINIMUM_CLUSTER_SIZE=11
MINIMUM_CONVERSION_LOCATIONS_FOR_CLUSTER=1
MINIMUM_CONVERSION_COUNT_FOR_CLUSTER=1
MINIMUM_READ_COUNT_FOR_CLUSTER_INCLUSION=5
MINIMUM_READ_LENGTH=1
MAXIMUM_NUMBER_OF_NON_CONVERSION_MISMATCHES=0

EXTEND_BY_READ

#ADDITIONAL_NUCLEOTIDES_BEYOND_SIGNAL=20

SAM_FILE=/Users/bieniaszlab/miniconda3/data/hnRNP_U/hg19_NL4_3/hnRNPU_NL43.sort.sam=COLLAPSED
GENOME_2BIT_FILE=/Users/bieniaszlab/miniconda3/data/hnRNP_U/hg19_NL4_3/NL43.2bit

OUTPUT_DISTRIBUTIONS_FILE=/Users/bieniaszlab/miniconda3/data/hnRNP_U/hg19_NL4_3/hnRNPU_NL43_distribution.csv
OUTPUT_GROUPS_FILE=/Users/bieniaszlab/miniconda3/data/hnRNP_U/hg19_NL4_3/hnRNPU_NL43_groups.csv
OUTPUT_CLUSTERS_FILE=/Users/bieniaszlab/miniconda3/data/hnRNP_U/hg19_NL4_3/hnRNPU_NL43_clusters.csv

Thanks,

Xiao

**Comment by KatsutomoNAIST** [comment]
Hi Xiao,

Thanks for your attention. 
I am writing to ask whether you solve this problem, since I met with the same problem.

Running PARalyzer v1.5
Parsing SAM file(s)...Done
Creating Read Groups & Clusters...Exception in thread "main" java.lang.Exception: * is not found in the .2bit file
        at MyTwoBitParser.loadChromosome(MyTwoBitParser.java:58)
        at MyTwoBitParser.getSequence(MyTwoBitParser.java:118)
        at PARalyze.main(PARalyze.java:204)

I am looking forward to your suggestions.
Thanks for your help. 

Best wishes,
Li Ze

**Comment by santataRU** [comment]
I found we have to filter unmapped reads out from sorted.bam file and only use sorted.sam file containing mapped reads.

Try use command, `samtools view -h -F 4 input.sorted.bam > output.sorted.sam ` and use the output.sorted.sam in the .ini file of PARAlyzer.

Xiao
